---
apiVersion: v1
kind: Service
metadata:
  name: islandora-crayfits
spec:
  selector:
    app: islandora-crayfits
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-crayfits
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-crayfits
  template:
    metadata:
      labels:
        app: islandora-crayfits
    spec:
      initContainers:
        - name: wait-for-fits
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until wget -qO- http://fits:8888/fits/version; do echo waiting for fits; sleep 5; done']
      containers:
        - name: fits
          image: islandora/fits:3.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: FITS_MAX_REQUEST_SIZE
              value: "100000"
            - name: FITS_MAX_UPLOAD_FILE_SIZE
              value: "100000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
          ports:
            - containerPort: 8080
              hostPort: 8888
          readinessProbe:
            httpGet:
              path: /fits/version
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: scyllaridae-crayfits
          image: __DOCKER_REPOSITORY__/scyllaridae-fits:main
          imagePullPolicy: IfNotPresent
          env:
            - name: SCYLLARIDAE_YML
              value: |
                allowedMimeTypes:
                  - "*"
                cmdByMimeType:
                  default:
                    cmd: "curl"
                    args:
                      - "-X"
                      - "POST"
                      - "-F"
                      - "datafile=@-"
                      - "http://fits:8888/fits/examine"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
