---
apiVersion: v1
kind: Service
metadata:
  name: islandora-whisper
spec:
  selector:
    app: islandora-whisper
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-whisper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-whisper
  template:
    metadata:
      labels:
        app: islandora-whisper
    spec:
      containers:
        - name: scyllaridae-whisper
          image: lehighlts/scyllaridae-whisper:main
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "5Gi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
