networks:
    default:
services:
    fits:
        image: islandora/fits:main@sha256:78ba37ab4771276e4e86577fbeb9dd1bd2f232b5a3e0383c3466c7acb6f58e10
    crayfits:
        image: lehighlts/scyllaridae-fits:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    ffmpeg:
        image: lehighlts/scyllaridae-ffmpeg:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    imagemagick:
        image: lehighlts/scyllaridae-imagemagick:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    tesseract:
        image: lehighlts/scyllaridae-tesseract:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    whisper:
        image: lehighlts/scyllaridae-whisper:${DOCKER_TAG}
        environment:
            SKIP_JWT_VERIFY: "true"
    pandoc:
        image: lehighlts/scyllaridae-pandoc:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    test:
        image: alpine@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
        command: sleep 300
        environment:
            DOCKER_TAG: ${DOCKER_TAG}
            ACTIONS_ID_TOKEN_REQUEST_URL: ${ACTIONS_ID_TOKEN_REQUEST_URL}
            ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
        volumes:
            - ./test.sh:/test.sh
            - ./fixtures:/fixtures
