networks:
    default:
services:
    fits:
        image: islandora/fits:main@sha256:38ee3fe6ce2ad0ff43b3dc7bdb2587300fcd696431395c2963ef706f7e7d00b6
    crayfits:
        image: lehighlts/scyllaridae-fits:${DOCKER_TAG}
    ffmpeg:
        image: lehighlts/scyllaridae-ffmpeg:${DOCKER_TAG}
    imagemagick:
        image: lehighlts/scyllaridae-imagemagick:${DOCKER_TAG}
    tesseract:
        image: lehighlts/scyllaridae-tesseract:${DOCKER_TAG}
    whisper:
        image: lehighlts/scyllaridae-whisper:${DOCKER_TAG}
    pandoc:
        image: lehighlts/scyllaridae-pandoc:${DOCKER_TAG}
    test:
        image: alpine@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099
        command: sleep 300
        environment:
            DOCKER_TAG: ${DOCKER_TAG}
        volumes:
            - ./test.sh:/test.sh
            - ./fixtures:/fixtures
