networks:
    default:
services:
    fits:
        image: islandora/fits:main@sha256:852d8530b17e5f7d3c5982a50a8ce6932ff90d6824678a9246c449421c5f67a3
    crayfits:
        image: lehighlts/scyllaridae-fits:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    ffmpeg:
        image: lehighlts/scyllaridae-ffmpeg:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    imagemagick:
        image: lehighlts/scyllaridae-imagemagick:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    tesseract:
        image: lehighlts/scyllaridae-tesseract:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    whisper:
        image: lehighlts/scyllaridae-whisper:${DOCKER_TAG}
        environment:
            SKIP_JWT_VERIFY: "true"
    pandoc:
        image: lehighlts/scyllaridae-pandoc:${DOCKER_TAG}
        environment:
            JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
    test:
        image: alpine@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
        command: sleep 300
        environment:
            DOCKER_TAG: ${DOCKER_TAG}
            ACTIONS_ID_TOKEN_REQUEST_URL: ${ACTIONS_ID_TOKEN_REQUEST_URL}
            ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
        volumes:
            - ./test.sh:/test.sh
            - ./fixtures:/fixtures
