networks:
    default:
services:
    fits:
        image: islandora/fits:main@sha256:2e8500ea08822935e7958fade7647c1ed080d43c6aae730511fe51ae9690b6a0
    crayfits:
        image: lehighlts/scyllaridae-fits:${DOCKER_TAG}
    ffmpeg:
        image: lehighlts/scyllaridae-ffmpeg:${DOCKER_TAG}
    imagemagick:
        image: lehighlts/scyllaridae-imagemagick:${DOCKER_TAG}
    tesseract:
        image: lehighlts/scyllaridae-tesseract:${DOCKER_TAG}
    whisper:
        image: lehighlts/scyllaridae-whisper:${DOCKER_TAG}
    pandoc:
        image: lehighlts/scyllaridae-pandoc:${DOCKER_TAG}
    test:
        image: alpine@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45
        command: sleep 300
        environment:
            DOCKER_TAG: ${DOCKER_TAG}
        volumes:
            - ./test.sh:/test.sh
            - ./fixtures:/fixtures
