networks:
    default:
services:
    fits:
        image: islandora/fits:main
    crayfits:
        image: lehighlts/scyllaridae-fits:${DOCKER_TAG}
    ffmpeg:
        image: lehighlts/scyllaridae-ffmpeg:${DOCKER_TAG}
    imagemagick:
        image: lehighlts/scyllaridae-imagemagick:${DOCKER_TAG}
    tesseract:
        image: lehighlts/scyllaridae-tesseract:${DOCKER_TAG}
    whisper:
        image: lehighlts/scyllaridae-whisper:${DOCKER_TAG}
    pandoc:
        image: lehighlts/scyllaridae-pandoc:${DOCKER_TAG}
    test:
        image: alpine
        command: sleep 300
        environment:
            DOCKER_TAG: ${DOCKER_TAG}
        volumes:
            - ./test.sh:/test.sh
            - ./fixtures:/fixtures
